name: PR Checks

on:
  pull_request:
    branches:
      - develop
      - feature/**

jobs:
  pr_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Dart & FVM
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.1.0' 

      - name: Install FVM & Flutter
        run: |
          dart pub global activate fvm
          fvm install 3.35.7
          fvm use 3.35.7

      - name: Install Dependencies
        run: fvm flutter pub get

      - name: Run Analyzer 
        run: fvm flutter analyze .


      - name: Check Formatting
        run: fvm dart format .